name: my-own-release-helper

on:
  issue_comment:
  
jobs:
  say-hi:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello world!
        run: echo "hello world!!!!!!!!!!"
        shell: bash






